# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "https://playagora.net"
baseurl: "/moonrise"
siteIcon: /media/android-chrome-192x192.png
siteYear: 2024
siteFooterlink: /about
showinSearchEngines: true
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: AgoraMC
serverDescription: Join mc.playagora.net:25588 – a semi-anarchy server where you can build, explore, and cause chaos with minimal rules. PvP, griefing, and freedom, with just enough order to keep it fun.
serverIP: mc.playagora.net:25588
useBedrockForOnlineStatus: false


# Discord information
discordInvite: https://discord.gg/JgNyMxtUtT
discordServerID: 1315555649723174924
discordChannelID: 1315569972164165682


# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
# siteNav:
#   - name: Server Map
#     url: map
#     newtab: true
#   - name: Screenshots
#     url: screenshots
#   - name: About
#     url: about


# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
